#!/usr/bin/env node
// Writes netlify.toml and vercel.json from deploy/policy.mjs. Run it after changing the
// policy; `npm test` fails if the checked-in files do not match what this produces.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GLOBAL_HEADERS, PATH_RULES, API_ROUTES } from '../deploy/policy.mjs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const BANNER = '# Generated by scripts/generate_deploy_config.mjs from deploy/policy.mjs. Do not edit by hand.';

const netlifyPattern = rule => (rule.match.exact ? rule.match.exact : `*${rule.match.extension}`);
const vercelPattern = rule => (rule.match.exact
  ? rule.match.exact
  : `/(.*)\\${rule.match.extension}`);

export function renderNetlifyToml() {
  const blocks = [
    BANNER,
    '',
    '[build]',
    '  publish = "public"',
    '  functions = "netlify/functions"',
    ''
  ];
  const emit = (pattern, headers) => {
    blocks.push('[[headers]]', `  for = "${pattern}"`, '  [headers.values]');
    for (const [key, value] of Object.entries(headers)) blocks.push(`    ${key} = "${value}"`);
    blocks.push('');
  };
  emit('/*', GLOBAL_HEADERS);
  for (const rule of PATH_RULES) emit(netlifyPattern(rule), rule.headers);
  for (const route of API_ROUTES) {
    blocks.push('[[redirects]]', `  from = "${route.path}"`, `  to = "/.netlify/functions/${route.function}"`, '  status = 200', '');
  }
  return blocks.join('\n').replace(/\n+$/, '\n');
}

export function renderVercelJson() {
  const headers = [{ source: '/(.*)', headers: Object.entries(GLOBAL_HEADERS).map(([key, value]) => ({ key, value })) }];
  for (const rule of PATH_RULES) {
    headers.push({ source: vercelPattern(rule), headers: Object.entries(rule.headers).map(([key, value]) => ({ key, value })) });
  }
  return JSON.stringify({
    $schema: 'https://openapi.vercel.sh/vercel.json',
    version: 2,
    public: true,
    cleanUrls: true,
    comment: 'Generated by scripts/generate_deploy_config.mjs from deploy/policy.mjs. Do not edit by hand.',
    headers
  }, null, 2) + '\n';
}

if (process.argv[1] && process.argv[1].endsWith('generate_deploy_config.mjs')) {
  fs.writeFileSync(path.join(root, 'netlify.toml'), renderNetlifyToml());
  fs.writeFileSync(path.join(root, 'vercel.json'), renderVercelJson());
  console.log('Wrote netlify.toml and vercel.json from deploy/policy.mjs.');
}
